#!/bin/bash
set -e

if [ -z "$POSTGRES_NON_ROOT_USER" ] || [ -z "$POSTGRES_NON_ROOT_PASSWORD" ]; then
    echo "SETUP INFO: Skipping non-root user creation - env vars not set"
    exit 0
fi

echo "Creating non-root user: $POSTGRES_NON_ROOT_USER"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
CREATE USER "$POSTGRES_NON_ROOT_USER" WITH PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE "$POSTGRES_DB" TO "$POSTGRES_NON_ROOT_USER";
GRANT USAGE ON SCHEMA public TO "$POSTGRES_NON_ROOT_USER";
GRANT CREATE ON SCHEMA public TO "$POSTGRES_NON_ROOT_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$POSTGRES_NON_ROOT_USER";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$POSTGRES_NON_ROOT_USER";
EOF

echo "Non-root user created successfully"
